
public enum Client_CmdType {

    E_CMD_LOGIN_REQ,
    
    E_CMD_WHOELSE_REQ,
    E_CMD_WHOELSE_RSP,
    
    E_CMD_WHOLASTH_REQ,
    E_CMD_WHOLASTH_RSP,
    
    E_CMD_BROADCAST_REQ,
    E_CMD_BROADCAST_RSP,
    
    E_CMD_MESSAGE_REQ,
    E_CMD_MESSAGE_RSP,
    E_CMD_MESSAGE_REJ,
    E_CMD_OFFLINE_MSG_IND,
    
    E_CMD_LOGOUT_REQ,

    E_CMD_BLOCK_REQ,
    E_CMD_UNBLOCK_REQ,
    
    E_CMD_INVALID_CMD
}