 public enum Server_CmdType {
    M_SERV_CMD_INCOMING_CONN,
    M_SERV_CMD_SEND_COMM_OBJ,
    
    M_SERV_CMD_REQ_AUTH,
    M_SERV_CMD_RESP_AUTH_OK,
    M_SERV_CMD_RESP_AUTH_FAIL,
    
    M_SERV_CMD_RESP_WHOELSE,
    M_SERV_CMD_RESP_WHOELSELASTHR
}