public enum Server_CmdType {

    M_SERV_CMD_INCOMING_CONN,
    M_SERV_CMD_SEND_COMM_OBJ,
    M_SERV_CMD_SEND_STRING,
    
    M_SERV_CMD_RESP_LOGIN_OK,
    M_SERV_CMD_RESP_LOGIN_FAIL,
    M_SERV_CMD_RESP_WHOELSE
};